mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/polls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.detail, name='detail'),
    path('new', views.new, name='new'),
    path('create', views.create, name='create'),
    path('<int:id>/edit', views.edit, name='edit'),
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/delete', views.delete, name='delete'),
]

polls/models.py
from django.db import models

class Article(models.Model):
    content = models.CharField(max_length=255)
    user_name = models.CharField(max_length=255, null=True)
    def __str__(self):
        return self.content

polls/forms.py
from django import forms
from .models import Article

#forms.Formではフォーム要素の名前は自由に付けられる
class SearchForm(forms.Form):
    
    keyword = forms.CharField(label='検索', max_length=100) #フィールドを文字列型で定義

#データベースに書き込むためだけのフォーム
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields =('content', 'user_name')

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Article
from .forms import SearchForm
from .forms import ArticleForm

# 一覧
def index(request):
    # フォームデータを取得
    '''
    UserForm(request.GET)でGETメソッドで送られたフォームのデータを取得
    またrequest.GETによってそのままデータを受け取る
    '''
    searchForm = SearchForm(request.GET)
    '''
    is_validは、フォームに入力された値にエラーがないかをバリデートするメソッド
    例えば、IntegerFieldの項目に数値以外のものが入った場合や、必須の項目が空欄だった場合にエラーとなる
    '''
    if searchForm.is_valid():
        # 安全なデータを受け取る
        '''
        cleaned_dataは、バリデート後のデータを型に応じて一定のやり方で整形して返す
        例えば、DateFieldの項目に日付を文字列で入れたときに、常にdatetime.dateオブジェクトにしてくれる
        cleaned_dataを使うことで、その後の処理を行う際に自分でデータの整形をする手間が省ける
        is_valid() を呼び出して正常に検証されると(そして``is_valid()`` が True を返すと)、
        検証されたフォームデータは form.cleaned_data ディクショナリに格納される
        つまりis_valid()の結果がTrueのとき、form.cleaned_dataに情報が格納される。
        もっと言えばis_valid()を挟まないと入力データを参照することは出来ない。
        '''
        keyword = searchForm.cleaned_data['keyword']
        # 安全なデータを使ってオブジェクトを作成
        articles = Article.objects.filter(content__contains=keyword)
    else:
        # 最初にブラウザから呼び出されるときに使用するフォームクラスを指定
        searchForm = SearchForm()
        articles = Article.objects.all()

    context = {
        'message': 'Welcome my BBS',
        'articles': articles,
        'searchForm': searchForm
    }
    return render(request, 'polls/index.html', context)


# 詳細
def detail(request, id):
    article = get_object_or_404(Article, pk=id)
    context = {
        'message' : 'Show article' + str(id),
        'article' : article,
    }
    return render(request, 'polls/detail.html', context)


# 新規
def new(request):
    articleForm = ArticleForm()
    context = {
        'message' : 'New article.',
        'articleForm' : articleForm,
    }
    return render(request, 'polls/new.html', context)


# 作成
def create(request):
    if request.method == 'POST':
        articleForm = ArticleForm(request.POST)
        if articleForm.is_valid:
            article = articleForm.save()

    context = {
        'message': 'create article' + str(article.id),
        'article': article,
    }
    return render(request, 'polls/detail.html', context)


# 編集
def edit(request, id):
    return HttpResponse('Thais is edit. ' + str(id))

# 更新
def update(request, id):
    return HttpResponse('This is update. ' + str(id))

# 削除
def delete(request, id):
    article = get_object_or_404(Article, pk=id)
    article.delete()

    articles = Article.objects.all()
    context = {
        'message' : 'Delete article' + str(id),
        'articles' : articles,
    }
    return render(request, 'polls/index.html', context)

polls/templates/polls/base.html
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <title>bashakaの掲示板</title>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <style>body {padding-top: 80px;}</style>
    </head>
    <body>
        <nav class='navbar navbar-expand-md navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "polls:index" %}'>bashakaの掲示板</a>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

polls/templates/polls/detail.html
{% extends './base.html' %}
{% block content %}
    <h1>django html</h1>
    <p>{{message}}</p>
    <p>{{article.content}},{{article.user_name}}</p>
    <a href = '{% url "polls:index" %}' class='btn btn-outline-primary'>一覧</a>
{% endblock %}

polls/templates/polls/index.html
{% extends './base.html' %}
{% block content %}
    <h1>bashakaの掲示板</h1>
    <p>{{ message }}</p>
    {% if searchForm %}
    <!-- action:送信先URLの指定 -->
        <form action='{% url "polls:index" %}' method='get'>
            <div class='form-group'>
                {{searchForm}}
                <input type='submit' class='btn btn-outline-primary' value='OK'>
                <a href='{% url "polls:index" %}' class='btn btn-outline-secondary'>クリア</a>
            </div>
        </form>
    {% endif %}
    <table class='table table-striped table-hover'>
        {% for article in articles %}
        <tr>
            <td>{{article.content}}</td>
            <td>{{article.user_name}}</td>
            <td>
                <a href = '{% url "polls:detail" article.id %}' class='btn btn-outline-primary'>詳細</a>
                <a href = '{% url "polls:delete" article.id %}' class='btn btn-outline-secondary'>削除</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <p>
        <a href='{% url "polls:new" %}' class='btn btn-outline-primary'>新規作成</a>
    </p>
{% endblock %}

polls/templates/polls/new.html
{% extends './base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h1>{{message}}</h1>
    <form action='{% url "polls:create" %}' method='post' class='form'>
        {% csrf_token %}
        {% bootstrap_form articleForm layout='horizontal' %}
        <button type='submit' class='btn btn-outline-primary'>作成する</button>
        <a href='{% url "polls:index' class='btn btn-outline-secondary'>戻る</a>
    </form>
{% endblock %}